"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const LoginController_1 = __importDefault(require("../ApiControllers/LoginController"));
const UserController_1 = __importDefault(require("../ApiControllers/UserController"));
const ContactController_1 = __importDefault(require("../ApiControllers/ContactController"));
const NoteController_1 = __importDefault(require("../ApiControllers/NoteController"));
const LoginLogic_1 = __importDefault(require("../Logic/LoginLogic"));
const UserLogic_1 = __importDefault(require("../Logic/UserLogic"));
const ContactLogic_1 = __importDefault(require("../Logic/ContactLogic"));
const NoteLogic_1 = __importDefault(require("../Logic/NoteLogic"));
const LoginRepository_1 = __importDefault(require("../DataAccessRepositories/LoginRepository"));
const NoteRepository_1 = __importDefault(require("../DataAccessRepositories/NoteRepository"));
const ContactRepository_1 = __importDefault(require("../DataAccessRepositories/ContactRepository"));
const UserRepository_1 = __importDefault(require("../DataAccessRepositories/UserRepository"));
const loginRepository = new LoginRepository_1.default();
const userRepository = new UserRepository_1.default();
const contactRepository = new ContactRepository_1.default();
const noteRepository = new NoteRepository_1.default();
const loginLogic = new LoginLogic_1.default(loginRepository);
const userLogic = new UserLogic_1.default(userRepository);
const contactLogic = new ContactLogic_1.default(contactRepository);
const noteLogic = new NoteLogic_1.default(noteRepository);
const loginController = new LoginController_1.default(loginLogic);
const userController = new UserController_1.default(userLogic);
const contactController = new ContactController_1.default(contactLogic, noteLogic);
const noteController = new NoteController_1.default(noteLogic);
const router = (0, express_1.Router)();
router.post('/api/login', loginController.createLogin.bind(loginController));
router.get('/api/user', userController.getUser.bind(userController));
router.get('/api/contacts', contactController.getContacts.bind(contactController));
router.get('/api/contacts/:contactId', contactController.getContactById.bind(contactController));
router.post('/api/contacts', contactController.createContact.bind(contactController));
router.put('/api/contacts/:contactId', contactController.updateContact.bind(contactController));
router.post('/api/contacts/:contactId/notes', contactController.createNoteForContact.bind(contactController));
router.get('/api/notes', noteController.getNotes.bind(noteController));
router.get('/api/notes/:noteId', noteController.getNoteById.bind(noteController));
exports.default = router;
